<a href="https://colab.research.google.com/github/thaistavares-cell/TEC_IASenac_Exercicios/blob/main/notebook_exercicios_pandas_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exercícios de revisão — Upload de arquivo, Pandas e NumPy

Nesta atividade, você vai usar a planilha **`base_exercicios_alunos_pandas.xlsx`** para praticar leitura de arquivo, exploração de dados, filtros, tratamento simples e uma introdução ao **NumPy**.

> Professor: você pode pedir que os alunos resolvam primeiro sozinhos e depois fazer a correção em sala.

In [2]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/MyDrive/Colab Notebooks/base_exercicios_alunos_pandas.xlsx'
df = pd.read_excel(path)
print("Arquivo carregado com sucesso!")
df.head()

Mounted at /content/drive
Arquivo carregado com sucesso!

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
1,2,Bruno Lima,20.0,A,Desenvolvimento,6.0,7.5,5.0,Goiânia,GO,2025-02-12,920.0,Não,bruno.lima@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo

## 1. Importando as bibliotecas

Use esta célula para importar as bibliotecas necessárias.

In [3]:
import pandas as pd
import numpy as np

## 2. Carregando o arquivo

Se estiver no **Google Colab**, primeiro envie a planilha.

Se estiver no **Jupyter Notebook**, basta garantir que o arquivo está na mesma pasta do notebook.

## 3. Conhecendo a base

### Exercício 1
Mostre as **5 primeiras linhas** da base.

### Exercício 2
Mostre as **5 últimas linhas** da base.

### Exercício 3
Descubra:
- quantidade de linhas e colunas
- nomes das colunas
- tipos de dados

In [4]:
print(df.tail())

    id_aluno           nome  idade turma            curso  nota1  nota2  \
25        26    Zeca Barros   24.0     C  Desenvolvimento    6.1    5.8
26        27      Ana Clara   18.0     A               IA    8.5    9.0
27        28  Beatriz Moura   20.0     B              NaN    7.2    7.6
28        29   Caio Moreira   19.0     C            Dados    NaN    NaN
29        30  Daniela Pires   22.0     B  Desenvolvimento    8.4    8.9

    faltas    cidade   uf data_matricula  mensalidade bolsista  \
25    14.0   Goiânia   GO     2025-02-05        920.0      Não
26     2.0  Brasília   DF     2025-02-10        850.0      Sim
27     4.0  Brasília   DF     2025-02-21          NaN      Sim
28     NaN       NaN  NaN     2025-02-22        780.0      NaN
29     1.0  Brasília   DF     2025-02-11        920.0      sim

                      email status
25    zeca.barros@email.com  Risco
26      ana.clara@email.com  Ativo
27  beatriz.moura@email.com  Ativo
28                      NaN  Ativo
29  daniela.pires@email.com  Ativo

In [5]:
print(df.shape)

(30, 15)

In [7]:
print(df.columns)

Index(['id_aluno', 'nome', 'idade', 'turma', 'curso', 'nota1', 'nota2',
       'faltas', 'cidade', 'uf', 'data_matricula', 'mensalidade', 'bolsista',
       'email', 'status'],
      dtype='object')

## 4. Seleção de colunas

### Exercício 4
Mostre apenas as colunas:
- `nome`
- `curso`
- `turma`
- `nota1`

### Exercício 5
Crie um novo DataFrame chamado `df_notas` contendo:
- `nome`
- `nota1`
- `nota2`
- `faltas`

In [6]:
df[['nome', 'curso', 'turma', 'nota1']]

              nome            curso turma  nota1
0        Ana Clara               IA     A    8.5
1       Bruno Lima  Desenvolvimento     A    6.0
2      Carla Souza               IA     B    9.2
3      Diego Alves            Dados     B    5.5
4     Eduarda Melo            Dados     A    7.8
5     Felipe Rocha               IA     C    4.0
6   Gabriela Nunes  Desenvolvimento     C    8.0
7   Henrique Silva               IA     A    NaN
8    Isabela Costa            Dados     B    9.5
9       João Pedro  Desenvolvimento     A    6.7
10      Karen Dias            Dados     B    7.0
11     Lucas Matos               IA     C    3.5
12    Mariana Reis            Dados     A    8.8
13   Nicolas Prado  Desenvolvimento     B    5.9
14  Olivia Martins               IA     C   10.0
15     Paulo Vitor            Dados     A    6.3
16   Quezia Araújo               IA     B    7.4
17    Rafael Gomes  Desenvolvimento     C    4.8
18   Sara Teixeira            Dados     A    7.9
19   Thiago Mendes               IA     C    5.0
20   Ursula Ferraz            Dados     B    8.1
21  Vinicius Lopes  Desenvolvimento     A    6.9
22   Wesley Castro               IA     B    2.5
23   Ximena Duarte            Dados     C    9.1
24    Yasmin Rocha               IA     A    8.3
25     Zeca Barros  Desenvolvimento     C    6.1
26       Ana Clara               IA     A    8.5
27   Beatriz Moura              NaN     B    7.2
28    Caio Moreira            Dados     C    NaN
29   Daniela Pires  Desenvolvimento     B    8.4

In [7]:
df_notas = df[['nome', 'nota1', 'nota2', 'faltas']]
print("Novo DataFrame 'df_notas' criado!")
df_notas.head()

Novo DataFrame 'df_notas' criado!

           nome  nota1  nota2  faltas
0     Ana Clara    8.5    9.0     2.0
1    Bruno Lima    6.0    7.5     5.0
2   Carla Souza    9.2    NaN     1.0
3   Diego Alves    5.5    6.0     8.0
4  Eduarda Melo    7.8    8.1     NaN

## 5. Filtros

### Exercício 6
Filtre apenas os alunos do curso **IA**.

### Exercício 7
Filtre apenas os alunos com `nota1` maior ou igual a **7**.

### Exercício 8
Filtre apenas os alunos da turma **B** e do curso **Dados**.

### Exercício 9
Filtre os alunos com mais de **5 faltas**.

In [8]:
alunos_ia = df[df['curso'] == 'IA']
alunos_ia

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
7,8,Henrique Silva,23.0,A,IA,NaN,7.9,3.0,Formosa,GO,2025-02-05,850.0,Nao,henrique.silva@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo

In [9]:
notas_altas = df[df['nota1'] >= 7]
notas_altas

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
0,1,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
2,3,Carla Souza,19.0,B,IA,9.2,NaN,1.0,Brasília,DF,2025-02-15,850.0,Sim,carla.souza@email.com,Ativo
4,5,Eduarda Melo,21.0,A,Dados,7.8,8.1,NaN,Taguatinga,DF,2025-02-18,780.0,Sim,eduarda.melo@email.com,Ativo
6,7,Gabriela Nunes,18.0,C,Desenvolvimento,8.0,8.8,0.0,Brasília,DF,2025-02-09,920.0,SIM,gabriela.nunes@email.com,Ativo
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo
16,17,Quezia Araújo,23.0,B,IA,7.4,8.2,2.0,Brasília,DF,2025-02-17,850.0,Sim,quezia.araujo@email.com,Ativo
18,19,Sara Teixeira,18.0,A,Dados,7.9,8.0,3.0,Sobradinho,DF,2025-02-19,780.0,Sim,sara.teixeira@email.com,Ativo
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo
27,28,Beatriz Moura,20.0,B,NaN,7.2,7.6,4.0,Brasília,DF,2025-02-21,NaN,Sim,beatriz.moura@email.com,Ativo
29,30,Daniela Pires,22.0,B,Desenvolvimento,8.4,8.9,1.0,Brasília,DF,2025-02-11,920.0,sim,daniela.pires@email.com,Ativo

In [10]:
turma_b_dados = df[(df['turma'] == 'B') & (df['curso'] == 'Dados')]
turma_b_dados

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
20,21,Ursula Ferraz,22.0,B,Dados,8.1,8.3,1.0,Brasília,DF,2025-02-18,780.0,Sim,ursula.ferraz@email.com,Ativo

In [11]:
muitas_faltas = df[df['faltas'] > 5]
muitas_faltas

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
5,6,Felipe Rocha,22.0,C,IA,4.0,5.5,12.0,Luziânia,GO,2025-02-08,850.0,Não,felipe.rocha@email.com,Inativo
10,11,Karen Dias,24.0,B,Dados,7.0,7.0,6.0,brasília,df,2025-02-16,780.0,Sim,karen.dias@email.com,Ativo
11,12,Lucas Matos,18.0,C,IA,3.5,4.5,15.0,Valparaíso,GO,2025-02-07,850.0,Não,NaN,Inativo
13,14,Nicolas Prado,20.0,B,Desenvolvimento,5.9,6.8,7.0,Gama,DF,2025-02-10,920.0,Não,nicolas.prado@email.com,Risco
15,16,Paulo Vitor,22.0,A,Dados,6.3,5.9,9.0,Cidade Ocidental,GO,2025-02-12,780.0,Não,paulo.vitor@email.com,Risco
17,18,Rafael Gomes,20.0,C,Desenvolvimento,4.8,NaN,11.0,Planaltina,DF,2025-02-06,920.0,Não,rafael.gomes@email.com,Inativo
19,20,Thiago Mendes,21.0,C,IA,5.0,5.2,10.0,Águas Lindas,GO,2025-02-01,850.0,Não,thiago.mendes@email.com,Risco
22,23,Wesley Castro,20.0,B,IA,2.5,3.0,18.0,Brasília,DF,2025-02-02,850.0,Não,wesley.castro@email.com,Inativo
25,26,Zeca Barros,24.0,C,Desenvolvimento,6.1,5.8,14.0,Goiânia,GO,2025-02-05,920.0,Não,zeca.barros@email.com,Risco

## 6. Valores nulos

### Exercício 10
Verifique quantos valores nulos existem em cada coluna.

### Exercício 11
Mostre apenas as linhas onde a coluna `idade` está nula.

### Exercício 12
Preencha os valores nulos de `nota1` com a média da coluna `nota1`.

In [12]:
df.isnull().sum()

id_aluno          0
nome              0
idade             2
turma             0
curso             1
nota1             2
nota2             3
faltas            2
cidade            1
uf                1
data_matricula    0
mensalidade       1
bolsista          1
email             2
status            0
dtype: int64

In [13]:
df[df['idade'].isnull()]

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status
3,4,Diego Alves,NaN,B,Dados,5.5,6.0,8.0,Anápolis,GO,2025-02-20,780.0,Não,diego.alves@email.com,Risco
24,25,Yasmin Rocha,NaN,A,IA,8.3,8.7,2.0,Brasília,DF,2025-02-15,850.0,Sim,yasmin.rocha@email.com,Ativo

In [17]:
media_nota1 = df['nota1'].mean()
df['nota1'] = df['nota1'].fillna(media_nota1)
print(f"Média aplicada: {media_nota1:.2f}")
print(df['nota1'].isnull().sum())

Média aplicada: 7.03
0

## 7. Tratamento de texto e padronização

### Exercício 13
Padronize a coluna `bolsista` para ficar apenas com:
- `Sim`
- `Não`

Dica: existem valores como `SIM`, `sim`, `Nao`.

### Exercício 14
Padronize a coluna `uf` para letras maiúsculas.

### Exercício 15
Padronize a coluna `cidade` no formato título.
Exemplo:
- `brasília` → `Brasília`

In [14]:
correcoes = {
    'SIM': 'Sim',
    'sim': 'Sim',
    'Nao': 'Não',
    'nao': 'Não',
    'NÃO': 'Não'
}
df['bolsista'] = df['bolsista'].replace(correcoes)
print(df['bolsista'].unique())

['Sim' 'Não' nan]

In [15]:
df['uf'] = df['uf'].str.upper()
df[['nome', 'uf']].head()

           nome  uf
0     Ana Clara  DF
1    Bruno Lima  GO
2   Carla Souza  DF
3   Diego Alves  GO
4  Eduarda Melo  DF

In [16]:
df['cidade'] = df['cidade'].str.title()
df[['nome', 'cidade']].head()

           nome      cidade
0     Ana Clara    Brasília
1    Bruno Lima     Goiânia
2   Carla Souza    Brasília
3   Diego Alves    Anápolis
4  Eduarda Melo  Taguatinga

## 8. Criando novas colunas

### Exercício 16
Crie uma coluna chamada `media` com a média entre `nota1` e `nota2`.

### Exercício 17
Crie uma coluna chamada `aprovado`:
- `True` para média maior ou igual a **7**
- `False` caso contrário

### Exercício 18
Crie uma coluna chamada `situacao_faltas`:
- `Alto risco` para mais de 10 faltas
- `Atenção` para 6 a 10 faltas
- `Ok` para até 5 faltas

In [17]:
df['media'] = (df['nota1'] + df['nota2']) / 2
df[['nome', 'nota1', 'nota2', 'media']].head()

           nome  nota1  nota2  media
0     Ana Clara    8.5    9.0   8.75
1    Bruno Lima    6.0    7.5   6.75
2   Carla Souza    9.2    NaN    NaN
3   Diego Alves    5.5    6.0   5.75
4  Eduarda Melo    7.8    8.1   7.95

In [18]:
df['aprovado'] = df['media'] >= 7
df[['nome', 'media', 'aprovado']].head()

           nome  media  aprovado
0     Ana Clara   8.75      True
1    Bruno Lima   6.75     False
2   Carla Souza    NaN     False
3   Diego Alves   5.75     False
4  Eduarda Melo   7.95      True

In [19]:
import numpy as np
condicoes = [
    (df['faltas'] > 10),
    (df['faltas'] >= 6) & (df['faltas'] <= 10),
    (df['faltas'] <= 5)
]
escolhas = ['Alto risco', 'Atenção', 'Ok']
df['situacao_faltas'] = np.select(condicoes, escolhas, default='N/A')
df[['nome', 'faltas', 'situacao_faltas']].head(10)

             nome  faltas situacao_faltas
0       Ana Clara     2.0              Ok
1      Bruno Lima     5.0              Ok
2     Carla Souza     1.0              Ok
3     Diego Alves     8.0         Atenção
4    Eduarda Melo     NaN             N/A
5    Felipe Rocha    12.0      Alto risco
6  Gabriela Nunes     0.0              Ok
7  Henrique Silva     3.0              Ok
8   Isabela Costa     1.0              Ok
9      João Pedro     4.0              Ok

## 9. Ordenação, contagem e agrupamento

### Exercício 19
Ordene os alunos pela coluna `media`, do maior para o menor.

### Exercício 20
Conte quantos alunos existem em cada curso.

### Exercício 21
Mostre a média de `nota1` por curso.

### Exercício 22
Mostre a média de faltas por turma.

In [20]:
df_ordenado = df.sort_values(by='media', ascending=False)
df_ordenado.head()

,id_aluno,nome,idade,turma,curso,nota1,nota2,faltas,cidade,uf,data_matricula,mensalidade,bolsista,email,status,media,aprovado,situacao_faltas
14,15,Olivia Martins,19.0,C,IA,10.0,9.8,0.0,Brasília,DF,2025-02-03,850.0,Sim,olivia.martins@email.com,Ativo,9.90,True,Ok
8,9,Isabela Costa,20.0,B,Dados,9.5,9.7,1.0,Brasília,DF,2025-02-11,780.0,Sim,isabela.costa@email.com,Ativo,9.60,True,Ok
23,24,Ximena Duarte,21.0,C,Dados,9.1,9.0,0.0,Taguatinga,DF,2025-02-04,780.0,Sim,ximena.duarte@email.com,Ativo,9.05,True,Ok
12,13,Mariana Reis,21.0,A,Dados,8.8,9.1,2.0,Brasília,DF,2025-02-14,780.0,Sim,mariana.reis@email.com,Ativo,8.95,True,Ok
26,27,Ana Clara,18.0,A,IA,8.5,9.0,2.0,Brasília,DF,2025-02-10,850.0,Sim,ana.clara@email.com,Ativo,8.75,True,Ok

In [22]:
contagem_cursos = df['curso'].value_counts()

print("Quantidade de alunos por curso:")
print(contagem_cursos)

Quantidade de alunos por curso:
curso
IA                 11
Dados              10
Desenvolvimento     8
Name: count, dtype: int64

In [23]:
media_por_curso = df.groupby('curso')['nota1'].mean()
print("Média da Nota 1 por curso:")
print(media_por_curso)

Média da Nota 1 por curso:
curso
Dados              7.777778
Desenvolvimento    6.600000
IA                 6.690000
Name: nota1, dtype: float64

In [24]:
media_faltas_turma = df.groupby('turma')['faltas'].mean()
print("Média de faltas por turma:")
print(media_faltas_turma)

Média de faltas por turma:
turma
A    3.70
B    4.90
C    7.75
Name: faltas, dtype: float64

## 10. Duplicatas e qualidade dos dados

### Exercício 23
Verifique se existem linhas duplicadas.

### Exercício 24
Remova as duplicatas e salve em um novo DataFrame chamado `df_limpo`.

### Exercício 25
Mostre os registros com emails possivelmente inválidos.
Dica: procure emails sem `@` ou sem `.com`.

In [25]:
total_duplicadas = df.duplicated().sum()

print(f"Existem {total_duplicadas} linhas duplicadas na base.")

Existem 0 linhas duplicadas na base.

In [26]:
df_limpo = df.drop_duplicates()

print(f"Tamanho original: {df.shape[0]} linhas")
print(f"Tamanho após a limpeza: {df_limpo.shape[0]} linhas")

Tamanho original: 30 linhas
Tamanho após a limpeza: 30 linhas

In [29]:
emails_invalidos = df_limpo[
    (~df_limpo['email'].str.contains('@', na=False)) |
    (~df_limpo['email'].str.contains('.com', na=False))
]

print("Registros com e-mails possivelmente inválidos (incluindo os vazios):")
emails_invalidos[['nome', 'email']]

Registros com e-mails possivelmente inválidos (incluindo os vazios):

            nome             email
9     João Pedro  joao.pedro@email
11   Lucas Matos               NaN
28  Caio Moreira               NaN

## 11. Salvando um novo arquivo

### Exercício 26
Salve o DataFrame tratado em um novo arquivo Excel chamado:
`base_tratada_alunos.xlsx`

In [30]:
caminho_destino = '/content/drive/MyDrive/Colab Notebooks/base_tratada_alunos.xlsx'
df_limpo.to_excel(caminho_destino, index=False)
print(f"Sucesso! O arquivo foi salvo em: {caminho_destino}")

Sucesso! O arquivo foi salvo em: /content/drive/MyDrive/Colab Notebooks/base_tratada_alunos.xlsx

## 12. Introdução ao NumPy

### Exercício 27
Crie um array NumPy com os valores da coluna `nota1`, removendo os nulos.

### Exercício 28
Com esse array, calcule:
- média
- maior valor
- menor valor
- soma

### Exercício 29
Some **1 ponto** em todas as notas do array.

### Exercício 30
Mostre apenas as notas maiores que **7** usando NumPy.

In [31]:


import numpy as np
notas_array = df_limpo['nota1'].dropna().to_numpy()
print("Array de notas criado com sucesso!")
print(notas_array)

Array de notas criado com sucesso!
[ 8.5  6.   9.2  5.5  7.8  4.   8.   9.5  6.7  7.   3.5  8.8  5.9 10.
  6.3  7.4  4.8  7.9  5.   8.1  6.9  2.5  9.1  8.3  6.1  8.5  7.2  8.4]

In [32]:
media = np.mean(notas_array)
maior = np.max(notas_array)
menor = np.min(notas_array)
soma = np.sum(notas_array)
print(f"Média: {media:.2f}")
print(f"Maior nota: {maior}")
print(f"Menor nota: {menor}")
print(f"Soma total: {soma}")

Média: 7.03
Maior nota: 10.0
Menor nota: 2.5
Soma total: 196.89999999999998

In [33]:
notas_bonus = notas_array + 1
print("Notas com bônus de 1 ponto:")
print(notas_bonus)

Notas com bônus de 1 ponto:
[ 9.5  7.  10.2  6.5  8.8  5.   9.  10.5  7.7  8.   4.5  9.8  6.9 11.
  7.3  8.4  5.8  8.9  6.   9.1  7.9  3.5 10.1  9.3  7.1  9.5  8.2  9.4]

In [34]:
notas_altas_np = notas_array[notas_array > 7]

print("Notas maiores que 7 (via NumPy):")
print(notas_altas_np)

Notas maiores que 7 (via NumPy):
[ 8.5  9.2  7.8  8.   9.5  8.8 10.   7.4  7.9  8.1  9.1  8.3  8.5  7.2
  8.4]

## 13. Desafio final

### Exercício 31 — Desafio
Monte uma análise final respondendo:

1. Quantos alunos há em cada curso?
2. Qual curso tem a maior média de `nota1`?
3. Quantos alunos têm mais de 10 faltas?
4. Quantos alunos são bolsistas?
5. Há dados faltando? Em quais colunas?
6. Há duplicatas?
7. Gere um DataFrame final apenas com:
   - `nome`
   - `curso`
   - `media`
   - `aprovado`

Depois, ordene esse DataFrame pela `media` em ordem decrescente.

In [35]:
import pandas as pd
import numpy as np

print("📊 --- RELATÓRIO FINAL DE DESEMPENHO --- 📊\n")


print("1. Distribuição de alunos por curso:")
print(df_limpo['curso'].value_counts())
print("-" * 40)
medias_cursos = df_limpo.groupby('curso')['nota1'].mean()
curso_top = medias_cursos.idxmax()
print(f"2. O curso com a maior média de Nota 1 é: {curso_top} (Média: {medias_cursos.max():.2f})")
print("-" * 30)
total_faltas_critico = df_limpo[df_limpo['faltas'] > 10].shape[0]
print(f"3. Alunos com mais de 10 faltas (Alto Risco): {total_faltas_critico}")
print("-" * 30)
total_bolsistas = df_limpo[df_limpo['bolsista'] == 'Sim'].shape[0]
print(f"4. Total de alunos bolsistas: {total_bolsistas}")
print("-" * 30)
nulos = df_limpo.isnull().sum()
print("5. Dados faltando por coluna:")
print(nulos[nulos > 0] if nulos.sum() > 0 else "Nenhum dado faltando no df_limpo.")
print("-" * 30)
total_dups = df_limpo.duplicated().sum()
print(f"6. Total de linhas duplicadas no df_limpo: {total_dups}")
print("-" * 40)
df_final = df_limpo[['nome', 'curso', 'media',
'aprovado']].sort_values(by='media', ascending=False)
print("\n --- DATAFRAME FINAL PARA ENTREGA --- ")
df_final.head(10)

📊 --- RELATÓRIO FINAL DE DESEMPENHO --- 📊

1. Distribuição de alunos por curso:
curso
IA                 11
Dados              10
Desenvolvimento     8
Name: count, dtype: int64
----------------------------------------
2. O curso com a maior média de Nota 1 é: Dados (Média: 7.78)
------------------------------
3. Alunos com mais de 10 faltas (Alto Risco): 5
------------------------------
4. Total de alunos bolsistas: 16
------------------------------
5. Dados faltando por coluna:
idade          2
curso          1
nota1          2
nota2          3
faltas         2
cidade         1
uf             1
mensalidade    1
bolsista       1
email          2
media          4
dtype: int64
------------------------------
6. Total de linhas duplicadas no df_limpo: 0
----------------------------------------

 --- DATAFRAME FINAL PARA ENTREGA ---

              nome            curso  media  aprovado
14  Olivia Martins               IA   9.90      True
8    Isabela Costa            Dados   9.60      True
23   Ximena Duarte            Dados   9.05      True
12    Mariana Reis            Dados   8.95      True
26       Ana Clara               IA   8.75      True
0        Ana Clara               IA   8.75      True
29   Daniela Pires  Desenvolvimento   8.65      True
24    Yasmin Rocha               IA   8.50      True
6   Gabriela Nunes  Desenvolvimento   8.40      True
20   Ursula Ferraz            Dados   8.20      True

## 14. Espaço para correção

Professor: aqui você pode ir resolvendo os exercícios em sala após os alunos tentarem.

In [ ]:
# Correção do professor